### ISSUE TITLE
'Settings' app crashes on 12.7.1

### ISSUE THREAD

**Issue by VladWinner** [RikkaApps/Sui#47]
```
FATAL EXCEPTION: main
Process: com.android.settings, PID: 22758
java.lang.IllegalArgumentException: Wrong number of arguments; expected 2, got 3
 at java.lang.reflect.Method.invoke(Native Method)
 at rikka.sui.settings.SettingsInstrumentation.callActivityOnNewIntent(SourceFile:7)
 at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:4317)
 at android.app.ActivityThread.handleNewIntent(ActivityThread.java:4324)
 at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
 at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:226)
 at android.os.Looper.loop(Looper.java:313)
 at android.app.ActivityThread.main(ActivityThread.java:8751)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
---
One UI 4.1, Android 12, Magisk 25205
Previous version of Sui (v12.6.3) doesn't cause such problems for me

**Comment by RikkaW** [comment]
This build (https://github.com/RikkaApps/Sui/actions/runs/3247985753) should solve your problem.
